version: "3.5"

services:
    ssh-server:
        image: linuxserver/openssh-server
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
            # - SUDO_ACCESS=true #optional
            - PASSWORD_ACCESS=true #optional
            - USER_PASSWORD=c0nv1d19 #optional
            - USER_NAME=convid19 #optional
        volumes: 
            - ./server:/config/ssh_host_keys
        ports:
            - 2222:2222
    
    server:
        image: local/whoami
        build: .
        ports: 
            - 8080:80
        environment: 
            - SSH_SERVER_HOST=ssh-server
            - SSH_SERVER_PORT=2222
            - SSH_LOCAL_HOST=localhost
            - SSH_LOCAL_PORT=80
            - SSH_REMOTE_HOST=localhost
            - SSH_REMOTE_PORT=8080
            - SSH_USER=convid19
            - SSH_PASSWORD=c0nv1d19
            - SSH_MODE=remote
    
    client:
        image: local/whoami
        build: .
        ports:
            - 5000:5000
        environment: 
            - SSH_SERVER_HOST=ssh-server
            - SSH_SERVER_PORT=2222
            - SSH_LOCAL_HOST=localhost
            - SSH_LOCAL_PORT=80
            - SSH_REMOTE_HOST=localhost
            - SSH_REMOTE_PORT=8080
            - SSH_USER=convid19
            - SSH_PASSWORD=c0nv1d19
            - SSH_MODE=local